//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADLogin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMaintainAD")]
    public interface IMaintainAD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaintainAD/CheckAccPwd", ReplyAction="http://tempuri.org/IMaintainAD/CheckAccPwdResponse")]
        bool CheckAccPwd(string account, string password, string AuthorizedAccount, string AuthorizedPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaintainAD/CheckAccPwd", ReplyAction="http://tempuri.org/IMaintainAD/CheckAccPwdResponse")]
        System.Threading.Tasks.Task<bool> CheckAccPwdAsync(string account, string password, string AuthorizedAccount, string AuthorizedPwd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaintainADChannel : ADLogin.ServiceReference1.IMaintainAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaintainADClient : System.ServiceModel.ClientBase<ADLogin.ServiceReference1.IMaintainAD>, ADLogin.ServiceReference1.IMaintainAD {
        
        public MaintainADClient() {
        }
        
        public MaintainADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaintainADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintainADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaintainADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckAccPwd(string account, string password, string AuthorizedAccount, string AuthorizedPwd) {
            return base.Channel.CheckAccPwd(account, password, AuthorizedAccount, AuthorizedPwd);
        }
        
        public System.Threading.Tasks.Task<bool> CheckAccPwdAsync(string account, string password, string AuthorizedAccount, string AuthorizedPwd) {
            return base.Channel.CheckAccPwdAsync(account, password, AuthorizedAccount, AuthorizedPwd);
        }
    }
}
